import argparse
import asyncio
import json
import os
import sqlite3
from datetime import UTC, datetime
from typing import Any, Literal

from dotenv import load_dotenv
from pydantic import BaseModel, Field
from pydantic_ai import Agent, FunctionToolset
from pydantic_ai.models.google import GoogleModel
from pydantic_ai.providers.google import GoogleProvider
from pydantic_ai.tools import RunContext

# from agent.models import

SYSTEM_PROMPT = """You are a GCSS-MC maintenance and supply data assistant.
Use the available SQLite query tool to answer questions about the database.
Only run read-only SELECT queries unless the user explicitly asks you to create an alert.
When querying, use the schema supplied in the user prompt as the source of truth.
Use the create_system_alert tool to inform marine analysts users of the following:
    - Identification of parts and equipment (specific or all) with chronic maintenance issues
    - Data quality issues arising from inconsistent, mislabeled, or missing data
    - Order pattern trends that negatively affect supply chain health
    - "End-items" that are frequently ordered but have high maintenance costs
    - Bottlenecks identified in the order fulfillment and acquisition process
Return a markdown-formatted report in the report field.

The database contains historical maintenance and supply data for the GCSS MC system.

Database schema:
{schema}
"""

DEFAULT_USER_PROMPT = """Review the GCSS MC database schema and identify anomalous data points.
Stakeholders would like to know which parts require a significant amount of maintenance consideration or cost.

Based on the data you find, identify which products or parts are problematic.
Provide a summary of the findings and any recommendations for stakeholders.
"""

load_dotenv()


class GCSSAgentDeps(BaseModel):
    """Per-run dependencies and mutable state for the GCSS agent."""

    sqlite_db_path: str
    db_schema: str
    queries_run: list[str] = Field(default_factory=list)
    system_alerts: list["SystemAlert"] = Field(default_factory=list)


class SystemAlert(BaseModel):
    """A system alert created during an agent run."""

    alert_name: str
    alert_description: str
    severity: Literal["low", "medium", "high", "critical"] = "medium"
    tamcn: str | None = None
    sr_number: str | None = None
    serial_number: str | None = None
    created_at: datetime
    updated_at: datetime


class AgentReport(BaseModel):
    """Structured, auditable output from a GCSS agent run."""

    report: str = Field(description="Markdown-formatted report generated by the agent.")
    queries_run: list[str] = Field(
        default_factory=list,
        description="Exact SQL queries run by the agent while generating the report.",
    )
    system_alerts: list[SystemAlert] = Field(
        default_factory=list,
        description="System alerts generated by the agent run.",
    )


# ----- Utility Functions -----
def get_db_schema(db_path: str) -> str:
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute("SELECT sql FROM sqlite_master WHERE type='table';")
    tables = cursor.fetchall()
    schema = "\n".join([table[0] for table in tables])
    conn.close()
    return schema


# ----- TOOLS -----
gcss_toolset = FunctionToolset[GCSSAgentDeps]()


@gcss_toolset.tool
def query_db(ctx: RunContext[GCSSAgentDeps], query: str) -> list[dict[str, Any]]:
    ctx.deps.queries_run.append(query)
    print(f"Executing query: {query}")

    conn = sqlite3.connect(ctx.deps.sqlite_db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute(query)
    rows = cursor.fetchall()
    results: list[dict[str, Any]] = [dict(row) for row in rows]
    conn.close()

    # Log results
    print(f"Results: {results}")
    return results


@gcss_toolset.tool
def create_system_alert(
    ctx: RunContext[GCSSAgentDeps],
    alert_name: str,
    alert_description: str,
    severity: Literal["low", "medium", "high", "critical"] = "medium",
    tamcn: str | None = None,
    sr_number: str | None = None,
    serial_number: str | None = None,
) -> None:
    """Creates a system alert, optionally linked to a TAMCN, service request, or serial number."""
    now = datetime.now(UTC)
    alert = SystemAlert(
        alert_name=alert_name,
        alert_description=alert_description,
        severity=severity,
        tamcn=tamcn,
        sr_number=sr_number,
        serial_number=serial_number,
        created_at=now,
        updated_at=now,
    )
    ctx.deps.system_alerts.append(alert)

    print(f"Created system alert: {alert_name}")

    conn = sqlite3.connect(ctx.deps.sqlite_db_path)
    cursor = conn.cursor()
    timestamp = format_utc_timestamp(now)
    cursor.execute(
        """
        INSERT INTO system_alerts (
            alert_name,
            alert_description,
            severity,
            tamcn,
            sr_number,
            serial_number,
            created_at,
            updated_at
        )
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
        (
            alert.alert_name,
            alert.alert_description,
            alert.severity,
            alert.tamcn,
            alert.sr_number,
            alert.serial_number,
            timestamp,
            timestamp,
        ),
    )
    conn.commit()
    conn.close()


gcss_tools = [
    query_db,
    create_system_alert,
]

MODEL_NAME = "gemini-3.1-pro-preview"


def format_utc_timestamp(value: datetime) -> str:
    """Return a stable UTC timestamp string for SQLite storage."""
    return value.isoformat(timespec="seconds").replace("+00:00", "Z")


def create_vertex_model() -> GoogleModel:
    """Create the Vertex AI-backed model definition."""
    provider = GoogleProvider(vertexai=True)
    return GoogleModel(MODEL_NAME, provider=provider)


def create_gemini_api_model() -> GoogleModel:
    """Create the Gemini API-backed model definition using GEMINI_API_KEY."""
    provider = GoogleProvider(api_key=os.environ.get("GEMINI_API_KEY"), vertexai=False)
    return GoogleModel(MODEL_NAME, provider=provider)


# ----- TESTING FNS -----


def query_db_test(db_path: str, query: str) -> list[dict[str, Any]]:
    # Log query
    print(f"Attempting query exec: {query}")

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute(query)
    rows = cursor.fetchall()
    results: list[dict[str, Any]] = [dict(row) for row in rows]
    conn.close()

    # Log results
    print(f"Results: {results}")
    print(f"Result type: {type(results)}")
    return results


def test_result():
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", type=str, required=True)
    args = parser.parse_args()
    # Test results
    results = query_db_test(args.db, "SELECT * FROM sr_parts LIMIT 10")
    print(results)
    print(type(results))


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--db", type=str, required=True)
    parser.add_argument(
        "prompt",
        nargs="?",
        default=None,
        help="Question or task for the GCSS agent. If omitted, the agent summarizes the database schema.",
    )
    args = parser.parse_args()

    # Get Database schema
    schema = get_db_schema(args.db)
    user_prompt = args.prompt or DEFAULT_USER_PROMPT.format(schema=schema)

    # GCSS Agent
    agent = Agent(
        model=create_gemini_api_model(),
        system_prompt=SYSTEM_PROMPT.format(schema=schema),
        deps_type=GCSSAgentDeps,
        output_type=AgentReport,
        tools=gcss_tools,
    )

    # Call agent, return answer
    deps = GCSSAgentDeps(sqlite_db_path=args.db, db_schema=schema)
    answer = asyncio.run(agent.run(user_prompt=user_prompt, deps=deps))
    output = answer.output.model_copy(
        update={
            "queries_run": deps.queries_run,
            "system_alerts": deps.system_alerts,
        }
    )
    print(json.dumps(output.model_dump(mode="json"), indent=2))
